import { useEffect, useState, type ReactNode } from 'react';
import { Icon } from '@iconify/react';
import { loadRequests, updateRequestStatus, useCms, supabase } from './data';
import { Shell } from './shell';
import { permissions, requestStatuses, messageStatuses, type CmsContent, type CmsItem, type FormDefinition, type FormField, type HomeCard, type HomeSection, type JoinRequest, type ServiceRequest } from './types';

type Tab = 'overview' | 'homepage' | 'pages' | 'services' | 'generalInfo' | 'initiatives' | 'videos' | 'payments' | 'reviews' | 'requests' | 'bookings' | 'messages' | 'roles' | 'company' | 'formLabels' | 'serviceForms' | 'joinForms' | 'joinRequests' | 'market' | 'testimonials';
const groups: { heading: string; items: [Tab, string, string][] }[] = [
  { heading: 'الرئيسية', items: [['overview', 'نظرة عامة', 'solar:widget-linear'], ['homepage', 'أقسام الرئيسية', 'solar:layers-linear'], ['pages', 'الصفحات', 'solar:document-text-linear']] },
  { heading: 'المحتوى', items: [['services', 'الخدمات', 'solar:box-linear'], ['generalInfo', 'خدمات خفيفة', 'solar:route-linear'], ['initiatives', 'المبادرات', 'solar:hand-heart-linear'], ['videos', 'الفيديوهات', 'solar:play-circle-linear'], ['reviews', 'الآراء', 'solar:star-linear'], ['market', 'عالم التقبيل', 'solar:buildings-linear'], ['testimonials', 'قالوا عنا', 'solar:videocamera-linear']] },
  { heading: 'النماذج والطلبات', items: [['serviceForms', 'نماذج الخدمات', 'solar:checklist-linear'], ['joinForms', 'نماذج انضم إلينا', 'solar:clipboard-list-linear'], ['formLabels', 'تسميات الفورم', 'solar:text-field-linear'], ['requests', 'طلبات العملاء', 'solar:inbox-linear'], ['bookings', 'الحجوزات', 'solar:calendar-linear'], ['messages', 'الرسائل', 'solar:letter-linear'], ['joinRequests', 'طلبات الانضمام', 'solar:user-plus-linear']] },
  { heading: 'الإعدادات', items: [['company', 'بيانات الشركة', 'solar:buildings-2-linear'], ['payments', 'المدفوعات', 'solar:card-linear'], ['roles', 'الصلاحيات', 'solar:shield-check-linear']] },
];
const fieldLabels: Record<string, string> = { titleAr: 'الاسم العربي', titleEn: 'الاسم الإنجليزي', description: 'الوصف', slug: 'الرابط المختصر', videoUrl: 'رابط الفيديو', nameAr: 'اسم الشركة', nameEn: 'الاسم الإنجليزي', taglineAr: 'الشعار النصي', taglineEn: 'الشعار النصي الإنجليزي', phone: 'الجوال', email: 'البريد الإلكتروني', website: 'الموقع الإلكتروني', headquarters: 'المقر', vat: 'الرقم الضريبي', cr: 'السجل التجاري', vision: 'الرؤية', mission: 'الرسالة', name: 'الاسم', sector: 'المجال', city: 'المدينة', status: 'الحالة', summary: 'الوصف المختصر', contactUrl: 'رابط التواصل', customer: 'اسم العميل', platform: 'المنصة', title: 'العنوان', body: 'النص', dateLabel: 'التاريخ / الحالة', rating: 'التقييم', kicker: 'العنوان الصغير', audience: 'الفئة المستهدفة', imageUrl: 'رابط الصورة', buttonLabel: 'نص الزر', target: 'الوجهة', paymentDescription: 'وصف الدفع', paymentPriceSar: 'السعر بالريال' };
function TextField({ label, value, onChange, multiline = false, type = 'text', placeholder }: { label: string; value: string | number; onChange: (value: string) => void; multiline?: boolean; type?: string; placeholder?: string }) {
  return <label className={`admin-field ${multiline ? 'admin-field-wide' : ''}`}><span>{label}</span>{multiline ? <textarea className="admin-input" rows={4} value={value} placeholder={placeholder} onChange={event => onChange(event.target.value)} /> : <input className="admin-input" type={type} value={value ?? ''} placeholder={placeholder} onChange={event => onChange(event.target.value)} />}</label>;
}
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: [string, string][] }) { return <label className="admin-field"><span>{label}</span><select className="admin-input" value={value} onChange={event => onChange(event.target.value)}>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>; }
function ToggleField({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <label className="admin-toggle"><input type="checkbox" checked={value} onChange={event => onChange(event.target.checked)} /><span>{label}</span></label>; }
function MiniButton({ icon, label, onClick, danger = false, disabled = false }: { icon: string; label: string; onClick: () => void; danger?: boolean; disabled?: boolean }) { return <button type="button" className={`mini-button ${danger ? 'mini-danger' : ''}`} onClick={onClick} title={label} aria-label={label} disabled={disabled}><Icon icon={icon} /> <span>{label}</span></button>; }
function RowActions({ moveUp, moveDown, remove }: { moveUp?: () => void; moveDown?: () => void; remove: () => void }) { return <div className="row-actions"><MiniButton icon="solar:arrow-up-linear" label="أعلى" onClick={moveUp || (() => {})} disabled={!moveUp} /><MiniButton icon="solar:arrow-down-linear" label="أسفل" onClick={moveDown || (() => {})} disabled={!moveDown} /><MiniButton icon="solar:trash-bin-trash-linear" label="حذف" onClick={remove} danger /></div>; }
function reorder<T>(items: T[], from: number, to: number) { const list = [...items]; if (to < 0 || to >= list.length) return list; const [item] = list.splice(from, 1); list.splice(to, 0, item); return list; }
function uniqueId(prefix: string) { return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`; }

function Login() {
  const { signIn, error: cmsError } = useCms(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  return <div className="admin-login"><div className="admin-login-copy"><span className="eyebrow">لوحة الإدارة</span><h1>مرحبًا بعودتك.</h1><p>إدارة محتوى وعاء والطلبات من مكان واحد.</p></div><form onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); try { await signIn(email, password); } catch (cause) { setError(cause instanceof Error ? cause.message : 'تعذر تسجيل الدخول.'); } finally { setBusy(false); } }}><h2>تسجيل الدخول</h2><TextField label="البريد الإلكتروني" value={email} onChange={setEmail} type="email" /><label className="admin-field"><span>كلمة المرور</span><input className="admin-input" type="password" required value={password} onChange={event => setPassword(event.target.value)} /></label>{error && <p className="error" role="alert">{error}</p>}{cmsError && <p className="admin-hint">تعذر تحديث المحتوى؛ تظهر بيانات المعاينة حتى يعود الاتصال.</p>}<button className="action action-primary" disabled={busy}>{busy ? 'جاري الدخول...' : 'دخول لوحة الإدارة'}</button></form></div>;
}
export function Admin() { const { user, authLoading, signOut, cms, error } = useCms(); const [tab, setTab] = useState<Tab>('overview'); const [navOpen, setNavOpen] = useState(false);
  return <Shell compact><div className="admin-page"><div className="admin-topbar"><div><span className="eyebrow">مساحة العمل</span><h1>إدارة وعاء</h1><p>{user ? `متصل بـ ${user.email}` : 'المحتوى والطلبات'}</p></div>{user && <div className="admin-top-actions"><button className="mini-button admin-mobile-menu" onClick={() => setNavOpen(previous => !previous)}><Icon icon="solar:menu-dots-linear" /> الأقسام</button><button className="mini-button" onClick={() => void signOut()}><Icon icon="solar:logout-linear" /> خروج</button></div>}</div>
    {authLoading ? <div className="admin-loading">جاري التحقق من الجلسة...</div> : !user ? <Login /> : <div className="admin-layout"><aside className={`admin-sidebar ${navOpen ? 'admin-sidebar-open' : ''}`} aria-label="أقسام الإدارة">{groups.map(group => <div key={group.heading}><h2>{group.heading}</h2>{group.items.map(([key, label, icon]) => <button type="button" key={key} className={tab === key ? 'active' : ''} onClick={() => { setTab(key); setNavOpen(false); }}><Icon icon={icon} />{label}</button>)}</div>)}</aside><div className="admin-main">{error && <div className="admin-warning" role="alert">تعذر تحديث المحتوى من Supabase؛ تحقق من الاتصال قبل الحفظ.</div>}<AdminBody key={tab} tab={tab} cms={cms} /></div></div>}
  </div></Shell>;
}

function AdminBody({ tab, cms }: { tab: Tab; cms: CmsContent }) {
  const { save, saving, saveError } = useCms(); const [draft, setDraft] = useState<CmsContent>(() => structuredClone(cms)); const [dirty, setDirty] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { setDraft(structuredClone(cms)); setDirty(false); setMessage(''); }, [cms, tab]);
  function change(next: CmsContent) { setDraft(next); setDirty(true); setMessage('تعديلات غير محفوظة'); }
  const patch = (key: keyof CmsContent, value: unknown) => change({ ...draft, [key]: value });
  const submit = async () => {
    if (draft.serviceModels.some(item => !item.slug?.trim()) || new Set(draft.serviceModels.map(item => item.slug)).size !== draft.serviceModels.length) { setMessage('روابط الخدمات يجب أن تكون غير فارغة وغير مكررة.'); return; }
    if (draft.joinForms.some(item => !item.slug?.trim()) || new Set(draft.joinForms.map(item => item.slug)).size !== draft.joinForms.length) { setMessage('روابط نماذج الانضمام يجب أن تكون غير فارغة وغير مكررة.'); return; }
    if (draft.companyListings.some(item => !item.slug?.trim()) || new Set(draft.companyListings.map(item => item.slug)).size !== draft.companyListings.length) { setMessage('روابط الشركات يجب أن تكون غير فارغة وغير مكررة.'); return; }
    const okay = await save(draft); setMessage(okay ? 'تم الحفظ' : 'تعذر الحفظ'); if (okay) setDirty(false);
  };
  const title = groups.flatMap(group => group.items).find(([key]) => key === tab)?.[1] || '';
  if (['requests', 'bookings', 'messages', 'joinRequests'].includes(tab)) return <RequestsPanel kind={tab as 'requests' | 'bookings' | 'messages' | 'joinRequests'} />;
  return <div><div className="admin-section-head"><div><span className="eyebrow">إدارة المحتوى</span><h2>{title}</h2></div>{tab !== 'overview' && <div className="save-actions"><span className={dirty ? 'unsaved' : ''}>{saving ? 'جاري الحفظ...' : saveError || message || 'لا توجد تعديلات'}</span><button className="action action-primary" type="button" disabled={!dirty || saving} onClick={() => void submit()}><Icon icon="solar:diskette-linear" /> حفظ التغييرات</button></div>}</div>
    {tab === 'overview' && <Overview cms={cms} />}
    {tab === 'pages' && <PagesEditor draft={draft} change={change} />}
    {(['services', 'generalInfo', 'initiatives'] as Tab[]).includes(tab) && <ItemsEditor collection={tab as 'services' | 'generalInfo' | 'initiatives'} draft={draft} patch={patch} />}
    {tab === 'videos' && <VideosEditor draft={draft} patch={patch} />}
    {tab === 'payments' && <PaymentsEditor draft={draft} patch={patch} />}
    {tab === 'reviews' && <ReviewsEditor draft={draft} patch={patch} />}
    {tab === 'company' && <CompanyEditor draft={draft} patch={patch} />}
    {tab === 'roles' && <RolesEditor draft={draft} patch={patch} />}
    {tab === 'formLabels' && <StringListEditor title="تسميات الحقول القديمة" items={draft.formLabels} change={items => patch('formLabels', items)} />}
    {tab === 'serviceForms' && <ServiceFormsEditor draft={draft} change={change} />}
    {tab === 'joinForms' && <JoinFormsEditor draft={draft} patch={patch} />}
    {tab === 'market' && <MarketEditor draft={draft} patch={patch} />}
    {tab === 'testimonials' && <TestimonialsEditor draft={draft} patch={patch} />}
    {tab === 'homepage' && <HomepageEditor draft={draft} patch={patch} />}
    {tab !== 'overview' && <div className="admin-bottom-save"><span>{dirty ? 'تعديلات غير محفوظة' : 'المحتوى محدث'}</span><button type="button" className="action action-primary" disabled={!dirty || saving} onClick={() => void submit()}>حفظ التغييرات</button></div>}
  </div>;
}

function Overview({ cms }: { cms: CmsContent }) { const cards = [['الصفحات', Object.keys(cms.pages).length], ['الخدمات', cms.serviceModels.length], ['نماذج الانضمام', cms.joinForms.length], ['الشركات', cms.companyListings.length], ['فيديوهات الآراء', cms.socialTestimonials.length], ['أقسام الرئيسية', cms.homepageSections.length]]; return <><div className="overview-grid">{cards.map(([label, count]) => <div key={label} className="overview-stat"><strong>{count}</strong><span>{label}</span></div>)}</div><div className="admin-note">بيانات العملاء والرسائل تظهر في أقسام الطلبات. الصلاحيات المعروضة داخل CMS وصفية وليست بديلًا عن سياسات Supabase.</div></>; }
function Panel({ title, children, actions }: { title: string; children: ReactNode; actions?: ReactNode }) { return <section className="admin-panel"><div className="admin-panel-head"><h3>{title}</h3>{actions}</div>{children}</section>; }
function PagesEditor({ draft, change }: { draft: CmsContent; change: (next: CmsContent) => void }) { const entries = Object.entries(draft.pages); const update = (key: string, field: string, value: string) => change({ ...draft, pages: { ...draft.pages, [key]: { ...draft.pages[key], [field]: value } } }); return <><button className="mini-button add-button" type="button" onClick={() => { const key = uniqueId('page'); change({ ...draft, pages: { ...draft.pages, [key]: { kicker: 'صفحة', title: 'صفحة جديدة', body: '' } } }); }}><Icon icon="solar:add-circle-linear" /> إضافة صفحة</button>{entries.map(([key, page]) => <Panel key={key} title={page.title || key} actions={<MiniButton icon="solar:trash-bin-trash-linear" label="حذف" danger onClick={() => { const next = { ...draft.pages }; delete next[key]; change({ ...draft, pages: next }); }} />}><p className="admin-hint">المعرّف: {key}</p><div className="admin-fields">{(['kicker', 'title', 'body'] as const).map(field => <TextField key={field} label={fieldLabels[field]} value={page[field]} onChange={value => update(key, field, value)} multiline={field === 'body'} />)}</div></Panel>)}</>; }
function StringListEditor({ title, items, change }: { title: string; items: string[]; change: (items: string[]) => void }) { return <Panel title={title}><div className="string-list">{items.map((item, index) => <div className="string-row" key={index}><input className="admin-input" value={item} onChange={event => change(items.map((entry, i) => i === index ? event.target.value : entry))} /><RowActions moveUp={index ? () => change(reorder(items, index, index - 1)) : undefined} moveDown={index < items.length - 1 ? () => change(reorder(items, index, index + 1)) : undefined} remove={() => change(items.filter((_, i) => i !== index))} /></div>)}</div><MiniButton icon="solar:add-circle-linear" label="إضافة" onClick={() => change([...items, ''])} /></Panel>; }
function ItemsEditor({ collection, draft, patch }: { collection: 'services' | 'generalInfo' | 'initiatives'; draft: CmsContent; patch: (key: keyof CmsContent, value: unknown) => void }) { const key = collection === 'services' ? 'serviceModels' : collection; const items = draft[key] as CmsItem[]; const update = (index: number, next: CmsItem) => patch(key, items.map((item, i) => i === index ? next : item)); return <><MiniButton icon="solar:add-circle-linear" label="إضافة عنصر" onClick={() => patch(key, [...items, { id: uniqueId('service'), titleAr: 'خدمة جديدة', titleEn: '', description: '', slug: uniqueId('service'), benefits: [], reviews: [], serviceCategory: collection === 'services' ? 'contracts' : 'light', paymentEnabled: false, paymentPriceSar: 0, paymentDescription: '' } satisfies CmsItem])} />{items.map((item, index) => <Panel key={item.id || index} title={item.titleAr || 'عنصر جديد'} actions={<RowActions moveUp={index ? () => patch(key, reorder(items, index, index - 1)) : undefined} moveDown={index < items.length - 1 ? () => patch(key, reorder(items, index, index + 1)) : undefined} remove={() => patch(key, items.filter((_, i) => i !== index))} />}><div className="admin-fields">{(['titleAr', 'titleEn', 'slug', 'description'] as const).map(field => <TextField key={field} label={fieldLabels[field]} value={item[field] || ''} multiline={field === 'description'} onChange={value => update(index, { ...item, [field]: value })} />)}<SelectField label="التصنيف" value={item.serviceCategory || 'light'} onChange={value => update(index, { ...item, serviceCategory: value })} options={[["light", "خدمات خفيفة"], ["contracts", "خدمات وعقود"]]} /></div><StringListEditor title="الفوائد والمخرجات" items={item.benefits || []} change={benefits => update(index, { ...item, benefits })} /></Panel>)}</>; }
function VideosEditor({ draft, patch }: { draft: CmsContent; patch: (key: keyof CmsContent, value: unknown) => void }) { return <>{draft.serviceModels.map((item, index) => <Panel key={item.id} title={item.titleAr}><TextField label="رابط YouTube" value={item.videoUrl || ''} onChange={videoUrl => patch('serviceModels', draft.serviceModels.map((service, i) => i === index ? { ...service, videoUrl } : service))} />{item.videoUrl && <a className="admin-link" href={item.videoUrl} target="_blank" rel="noopener noreferrer">فتح الرابط للتحقق <Icon icon="solar:arrow-up-left-linear" /></a>}</Panel>)}</>; }
function PaymentsEditor({ draft, patch }: { draft: CmsContent; patch: (key: keyof CmsContent, value: unknown) => void }) { return <><div className="admin-note">أسعار الخدمات تُحفظ في CMS. الدفع يتم من صفحة الخدمة عبر Supabase Edge Function وStripe.</div>{draft.serviceModels.map((item, index) => <Panel key={item.id} title={item.titleAr}><div className="admin-fields"><ToggleField label="تفعيل الدفع لهذه الخدمة" value={item.paymentEnabled} onChange={paymentEnabled => patch('serviceModels', draft.serviceModels.map((service, i) => i === index ? { ...service, paymentEnabled } : service))} /><TextField label="السعر بالريال" value={item.paymentPriceSar || 0} type="number" onChange={value => patch('serviceModels', draft.serviceModels.map((service, i) => i === index ? { ...service, paymentPriceSar: Math.max(0, Number(value) || 0) } : service))} /><TextField label="وصف الدفع" value={item.paymentDescription || ''} onChange={value => patch('serviceModels', draft.serviceModels.map((service, i) => i === index ? { ...service, paymentDescription: value } : service))} /></div></Panel>)}</>; }
function ReviewsEditor({ draft, patch }: { draft: CmsContent; patch: (key: keyof CmsContent, value: unknown) => void }) { const update = (index: number, next: CmsItem) => patch('serviceModels', draft.serviceModels.map((item, i) => i === index ? next : item)); return <>{draft.serviceModels.map((item, index) => <Panel key={item.id} title={item.titleAr}><MiniButton icon="solar:add-circle-linear" label="إضافة رأي" onClick={() => update(index, { ...item, reviews: [...item.reviews, { customer: '', body: '', dateLabel: '', rating: 5 }] })} />{item.reviews.map((review, reviewIndex) => <div className="review-editor" key={reviewIndex}><div className="admin-fields">{(['customer', 'body', 'dateLabel', 'rating'] as const).map(field => <TextField key={field} label={fieldLabels[field]} value={review[field]} type={field === 'rating' ? 'number' : 'text'} multiline={field === 'body'} onChange={value => update(index, { ...item, reviews: item.reviews.map((entry, i) => i === reviewIndex ? { ...entry, [field]: field === 'rating' ? Math.max(1, Math.min(5, Number(value) || 1)) : value } : entry) })} />)}</div><MiniButton icon="solar:trash-bin-trash-linear" label="حذف الرأي" danger onClick={() => update(index, { ...item, reviews: item.reviews.filter((_, i) => i !== reviewIndex) })} /></div>)}</Panel>)}</>; }
function CompanyEditor({ draft, patch }: { draft: CmsContent; patch: (key: keyof CmsContent, value: unknown) => void }) { return <Panel title="بيانات الشركة"><div className="admin-fields">{Object.entries(draft.company).map(([key, value]) => <TextField key={key} label={fieldLabels[key] || key} value={value} multiline={['vision', 'mission'].includes(key)} onChange={next => patch('company', { ...draft.company, [key]: next })} />)}</div></Panel>; }
function RolesEditor({ draft, patch }: { draft: CmsContent; patch: (key: keyof CmsContent, value: unknown) => void }) { return <><div className="admin-warning">هذه أدوار وصفية داخل CMS فقط. الحماية الفعلية تعتمد على Supabase Auth وRLS.</div><MiniButton icon="solar:add-circle-linear" label="إضافة دور" onClick={() => patch('adminRoles', [...draft.adminRoles, { id: uniqueId('role'), name: 'دور جديد', permissions: [] }])} />{draft.adminRoles.map((role, index) => <Panel key={role.id} title={role.name} actions={<MiniButton icon="solar:trash-bin-trash-linear" label="حذف" danger onClick={() => patch('adminRoles', draft.adminRoles.filter((_, i) => i !== index))} />}><TextField label="اسم الدور" value={role.name} onChange={name => patch('adminRoles', draft.adminRoles.map((entry, i) => i === index ? { ...entry, name } : entry))} /><div className="permission-grid">{permissions.map(permission => <ToggleField key={permission} label={permission} value={role.permissions.includes(permission)} onChange={checked => patch('adminRoles', draft.adminRoles.map((entry, i) => i === index ? { ...entry, permissions: checked ? [...entry.permissions, permission] : entry.permissions.filter(item => item !== permission) } : entry))} />)}</div></Panel>)}</>; }

function FormDefinitionEditor({ form, change, service = false }: { form: FormDefinition; change: (form: FormDefinition) => void; service?: boolean }) {
  const update = (key: keyof FormDefinition, value: unknown) => change({ ...form, [key]: value });
  const fields = form.fields || [];
  const updateField = (index: number, next: FormField) => update('fields', fields.map((field, i) => i === index ? next : field));
  const courier = form.submissionType.startsWith('courier-');
  return <div className="form-definition"><div className="admin-fields"><TextField label="عنوان النموذج" value={form.title} onChange={value => update('title', value)} /><TextField label="الرابط المختصر" value={form.slug} onChange={value => update('slug', value)} /><TextField label="الفئة المستهدفة" value={form.audience} onChange={value => update('audience', value)} /><TextField label="الوصف" value={form.description} multiline onChange={value => update('description', value)} /><ToggleField label="النموذج فعال" value={form.enabled} onChange={value => update('enabled', value)} /></div><div className="admin-subhead"><h4>حقول النموذج</h4>{!courier && <MiniButton icon="solar:add-circle-linear" label="إضافة حقل" onClick={() => update('fields', [...fields, { key: uniqueId('field'), label: 'حقل جديد', type: 'text', required: false, options: [] }])} />}</div>
    {courier && <div className="admin-note">حقول المناديب وقيمها الداخلية ثابتة لتوافق نظام الاستقبال؛ يمكنك تعديل عناوينها فقط.</div>}
    {fields.map((field, index) => <div className="form-field-editor" key={field.key}><div className="admin-fields"><TextField label="عنوان الحقل" value={field.label} onChange={label => updateField(index, { ...field, label })} />{!courier && <><TextField label="المعرّف الداخلي" value={field.key} onChange={key => updateField(index, { ...field, key })} /><SelectField label="نوع الحقل" value={field.type} onChange={type => updateField(index, { ...field, type: type as FormField['type'] })} options={['text', 'number', 'phone', 'email', 'date', 'select', 'multiline', 'file'].map(type => [type, ({ text: 'نص', number: 'رقم', phone: 'هاتف', email: 'بريد', date: 'تاريخ', select: 'اختيار', multiline: 'تفاصيل', file: 'ملف' } as Record<string, string>)[type]])} /><ToggleField label="حقل مطلوب" value={field.required} onChange={required => updateField(index, { ...field, required })} />{field.type === 'select' && <TextField label="الخيارات، مفصولة بفاصلة" value={field.options.join(', ')} onChange={value => updateField(index, { ...field, options: value.split(',').map(option => option.trim()).filter(Boolean) })} />}</>}</div>{!courier && <RowActions moveUp={index ? () => update('fields', reorder(fields, index, index - 1)) : undefined} moveDown={index < fields.length - 1 ? () => update('fields', reorder(fields, index, index + 1)) : undefined} remove={() => update('fields', fields.filter((_, i) => i !== index))} />}</div>)}
    {service && <div className="admin-note">الخدمة دون تخصيص تستخدم النموذج الافتراضي تلقائيًا.</div>}
  </div>;
}
function ServiceFormsEditor({ draft, change }: { draft: CmsContent; change: (next: CmsContent) => void }) { const [selected, setSelected] = useState('default'); const service = draft.serviceModels.find(item => item.slug === selected); const custom = selected !== 'default' ? draft.serviceFormOverrides[selected] : undefined; const form = custom || draft.defaultServiceForm; const update = (next: FormDefinition) => change(selected === 'default' ? { ...draft, defaultServiceForm: next } : { ...draft, serviceFormOverrides: { ...draft.serviceFormOverrides, [selected]: next } }); return <><div className="admin-toolbar"><SelectField label="اختر النموذج" value={selected} onChange={setSelected} options={[["default", "النموذج الافتراضي"], ...draft.serviceModels.filter(item => item.slug).map(item => [item.slug!, item.titleAr] as [string, string])]} />{selected !== 'default' && <>{!custom ? <MiniButton icon="solar:copy-linear" label="تخصيص الخدمة" onClick={() => change({ ...draft, serviceFormOverrides: { ...draft.serviceFormOverrides, [selected]: structuredClone({ ...draft.defaultServiceForm, slug: selected, id: `form:${selected}`, title: `طلب ${service?.titleAr || 'خدمة'}` }) } })} /> : <MiniButton icon="solar:restart-linear" label="العودة للافتراضي" onClick={() => { const next = { ...draft.serviceFormOverrides }; delete next[selected]; change({ ...draft, serviceFormOverrides: next }); }} />}</>}</div><Panel title={selected === 'default' ? 'النموذج الافتراضي للخدمات' : `نموذج ${service?.titleAr || selected}`}><FormDefinitionEditor form={form} change={update} service /></Panel></>; }
function JoinFormsEditor({ draft, patch }: { draft: CmsContent; patch: (key: keyof CmsContent, value: unknown) => void }) { const forms = draft.joinForms; const [selected, setSelected] = useState(forms[0]?.id || ''); const index = forms.findIndex(form => form.id === selected); const form = forms[index]; return <><div className="admin-toolbar"><SelectField label="اختر النموذج" value={selected} onChange={setSelected} options={forms.map(item => [item.id, item.title])} /><MiniButton icon="solar:add-circle-linear" label="إضافة نموذج" onClick={() => { const id = uniqueId('form'); const slug = uniqueId('join'); patch('joinForms', [...forms, { id, slug, title: 'نموذج جديد', description: '', audience: '', kind: 'join', enabled: true, submissionType: 'supabase', fields: [] }]); setSelected(id); }} />{form && <><MiniButton icon="solar:arrow-up-linear" label="أعلى" disabled={index === 0} onClick={() => patch('joinForms', reorder(forms, index, index - 1))} /><MiniButton icon="solar:arrow-down-linear" label="أسفل" disabled={index === forms.length - 1} onClick={() => patch('joinForms', reorder(forms, index, index + 1))} /><MiniButton icon="solar:trash-bin-trash-linear" label="حذف النموذج" danger onClick={() => { patch('joinForms', forms.filter((_, i) => i !== index)); setSelected(forms.find((_, i) => i !== index)?.id || ''); }} /></>}</div>{form && <Panel title={form.title}><FormDefinitionEditor form={form} change={next => patch('joinForms', forms.map((item, i) => i === index ? next : item))} /></Panel>}</>; }

function MarketEditor({ draft, patch }: { draft: CmsContent; patch: (key: keyof CmsContent, value: unknown) => void }) { const items = draft.companyListings; const update = (index: number, next: typeof items[number]) => patch('companyListings', items.map((item, i) => i === index ? next : item)); return <><MiniButton icon="solar:add-circle-linear" label="إضافة شركة" onClick={() => patch('companyListings', [...items, { slug: uniqueId('company'), name: 'شركة جديدة', sector: '', city: '', status: 'متاحة', summary: '', contactUrl: '', metadata: {}, enabled: false }])} />{items.map((item, index) => <Panel key={item.slug} title={item.name} actions={<RowActions moveUp={index ? () => patch('companyListings', reorder(items, index, index - 1)) : undefined} moveDown={index < items.length - 1 ? () => patch('companyListings', reorder(items, index, index + 1)) : undefined} remove={() => patch('companyListings', items.filter((_, i) => i !== index))} />}><div className="admin-fields">{(['name', 'slug', 'sector', 'city', 'status', 'summary', 'contactUrl'] as const).map(field => <TextField key={field} label={fieldLabels[field]} value={item[field]} multiline={field === 'summary'} onChange={value => update(index, { ...item, [field]: value })} />)}<ToggleField label="منشور" value={item.enabled} onChange={enabled => update(index, { ...item, enabled })} /></div><div className="admin-subhead"><h4>بيانات إضافية</h4><MiniButton icon="solar:add-circle-linear" label="إضافة معلومة" onClick={() => update(index, { ...item, metadata: { ...item.metadata, [`معلومة ${Object.keys(item.metadata).length + 1}`]: '' } })} /></div>{Object.entries(item.metadata).map(([key, value]) => <div className="metadata-row" key={key}><TextField label="الاسم" value={key} onChange={newKey => { const next = { ...item.metadata }; delete next[key]; next[newKey] = value; update(index, { ...item, metadata: next }); }} /><TextField label="القيمة" value={value} onChange={nextValue => update(index, { ...item, metadata: { ...item.metadata, [key]: nextValue } })} /><MiniButton icon="solar:trash-bin-trash-linear" label="حذف" danger onClick={() => { const next = { ...item.metadata }; delete next[key]; update(index, { ...item, metadata: next }); }} /></div>)}</Panel>)}</>; }
function TestimonialsEditor({ draft, patch }: { draft: CmsContent; patch: (key: keyof CmsContent, value: unknown) => void }) { const items = draft.socialTestimonials; const update = (index: number, next: typeof items[number]) => patch('socialTestimonials', items.map((item, i) => i === index ? next : item)); return <><MiniButton icon="solar:add-circle-linear" label="إضافة فيديو" onClick={() => patch('socialTestimonials', [...items, { id: uniqueId('testimonial'), customer: '', platform: '', title: 'تجربة جديدة', videoUrl: '', enabled: false }])} />{items.map((item, index) => <Panel key={item.id} title={item.title} actions={<RowActions moveUp={index ? () => patch('socialTestimonials', reorder(items, index, index - 1)) : undefined} moveDown={index < items.length - 1 ? () => patch('socialTestimonials', reorder(items, index, index + 1)) : undefined} remove={() => patch('socialTestimonials', items.filter((_, i) => i !== index))} />}><div className="admin-fields">{(['customer', 'platform', 'title', 'videoUrl'] as const).map(field => <TextField key={field} label={fieldLabels[field]} value={item[field]} onChange={value => update(index, { ...item, [field]: value })} />)}<ToggleField label="منشور" value={item.enabled} onChange={enabled => update(index, { ...item, enabled })} /></div></Panel>)}</>; }

function HomepageEditor({ draft, patch }: { draft: CmsContent; patch: (key: keyof CmsContent, value: unknown) => void }) { const sections = draft.homepageSections; const update = (index: number, next: HomeSection) => patch('homepageSections', sections.map((item, i) => i === index ? next : item)); return <><MiniButton icon="solar:add-circle-linear" label="إضافة قسم" onClick={() => patch('homepageSections', [...sections, { id: uniqueId('section'), title: 'قسم جديد', description: '', type: 'cards', imageUrl: '', enabled: true, cards: [] }])} />{sections.map((section, index) => <Panel key={section.id} title={section.title} actions={<RowActions moveUp={index ? () => patch('homepageSections', reorder(sections, index, index - 1)) : undefined} moveDown={index < sections.length - 1 ? () => patch('homepageSections', reorder(sections, index, index + 1)) : undefined} remove={() => patch('homepageSections', sections.filter((_, i) => i !== index))} />}><div className="admin-fields"><TextField label="العنوان" value={section.title} onChange={title => update(index, { ...section, title })} /><SelectField label="نوع العرض" value={section.type} onChange={type => update(index, { ...section, type })} options={[["hero", "هيرو"], ["bio", "نبذة وصورة"], ["cards", "بطاقات"], ["market", "عالم التقبيل"], ["contact", "تواصل"]]} /><TextField label="الوصف" value={section.description} multiline onChange={description => update(index, { ...section, description })} /><TextField label="رابط الصورة" value={section.imageUrl} onChange={imageUrl => update(index, { ...section, imageUrl })} /><ToggleField label="ظاهر على الموقع" value={section.enabled} onChange={enabled => update(index, { ...section, enabled })} /></div>{!['bio', 'contact'].includes(section.type) && <><div className="admin-subhead"><h4>البطاقات والأزرار</h4><MiniButton icon="solar:add-circle-linear" label="إضافة بطاقة" onClick={() => update(index, { ...section, cards: [...section.cards, { id: uniqueId('card'), title: 'بطاقة جديدة', description: '', imageUrl: '', buttonLabel: 'استكشف', destinationType: 'contact', target: '', enabled: true }] })} /></div>{section.cards.map((card, cardIndex) => <HomeCardEditor key={card.id} card={card} change={next => update(index, { ...section, cards: section.cards.map((item, i) => i === cardIndex ? next : item) })} actions={<RowActions moveUp={cardIndex ? () => update(index, { ...section, cards: reorder(section.cards, cardIndex, cardIndex - 1) }) : undefined} moveDown={cardIndex < section.cards.length - 1 ? () => update(index, { ...section, cards: reorder(section.cards, cardIndex, cardIndex + 1) }) : undefined} remove={() => update(index, { ...section, cards: section.cards.filter((_, i) => i !== cardIndex) })} />} />)}</>}</Panel>)}</>; }
function HomeCardEditor({ card, change, actions }: { card: HomeCard; change: (card: HomeCard) => void; actions: ReactNode }) {
  const { cms } = useCms();
  const destinationOptions: [string, string][] = card.destinationType === 'service'
    ? cms.serviceModels.map(item => [item.id, item.titleAr])
    : cms.joinForms.map(form => [form.id, form.title]);
  return <div className="home-card-editor">
    <div className="admin-subhead"><strong>{card.title}</strong>{actions}</div>
    <div className="admin-fields">
      {(['title', 'description', 'imageUrl', 'buttonLabel'] as const).map(field => <TextField key={field} label={fieldLabels[field]} value={card[field]} onChange={value => change({ ...card, [field]: value })} />)}
      <SelectField label="نوع الوجهة" value={card.destinationType} onChange={destinationType => change({ ...card, destinationType, target: '' })} options={[["page", "صفحة داخلية"], ["service", "خدمة"], ["form", "نموذج انضمام"], ["contact", "تواصل"], ["external", "رابط خارجي"], ["download", "تحميل ملف"]]} />
      {['service', 'form'].includes(card.destinationType)
        ? <SelectField label="الوجهة" value={card.target} onChange={target => change({ ...card, target })} options={[["", "اختر الوجهة"], ...destinationOptions]} />
        : card.destinationType !== 'contact' && <TextField label="الوجهة" value={card.target} placeholder={card.destinationType === 'page' ? '/services' : 'https://'} onChange={target => change({ ...card, target })} />}
      <ToggleField label="ظاهر" value={card.enabled} onChange={enabled => change({ ...card, enabled })} />
    </div>
  </div>;
}

function RequestsPanel({ kind }: { kind: 'requests' | 'bookings' | 'messages' | 'joinRequests' }) { const [data, setData] = useState<{ services: ServiceRequest[]; messages: ServiceRequest[]; joins: JoinRequest[] }>({ services: [], messages: [], joins: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [statusFilter, setStatusFilter] = useState('all'); const [busy, setBusy] = useState('');
  useEffect(() => { let alive = true; void loadRequests().then(next => { if (alive) setData(next); }).catch(cause => { if (alive) setError(cause instanceof Error ? cause.message : 'تعذر تحميل الطلبات.'); }).finally(() => { if (alive) setLoading(false); }); return () => { alive = false; }; }, []);
  const items = kind === 'joinRequests' ? data.joins : kind === 'messages' ? data.messages : kind === 'bookings' ? data.services.filter(item => ['قيد المتابعة', 'تم التواصل', 'مؤكد'].includes(item.status)) : data.services;
  const filtered = items.filter(item => (statusFilter === 'all' || item.status === statusFilter) && JSON.stringify(item).toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  const statuses = kind === 'messages' ? messageStatuses : requestStatuses;
  const heading = kind === 'joinRequests' ? 'طلبات الانضمام' : kind === 'messages' ? 'الرسائل' : kind === 'bookings' ? 'الحجوزات' : 'طلبات العملاء';
  const update = async (id: string, status: string) => { setBusy(id); setError(''); try { await updateRequestStatus(kind === 'joinRequests' ? 'join' : 'service', id, status); setData(previous => ({ ...previous, [kind === 'joinRequests' ? 'joins' : kind === 'messages' ? 'messages' : 'services']: previous[kind === 'joinRequests' ? 'joins' : kind === 'messages' ? 'messages' : 'services'].map(item => item.id === id ? { ...item, status } : item) })); } catch (cause) { setError(cause instanceof Error ? cause.message : 'تعذر تغيير الحالة.'); } finally { setBusy(''); } };
  return <><div className="admin-section-head"><div><span className="eyebrow">المتابعة</span><h2>{heading}</h2></div><strong>{filtered.length} نتيجة</strong></div><div className="admin-toolbar"><TextField label="بحث بالاسم أو الخدمة أو البريد" value={search} onChange={setSearch} /><SelectField label="الحالة" value={statusFilter} onChange={setStatusFilter} options={[["all", "كل الحالات"], ...statuses.map(item => [item, item] as [string, string])]} /><MiniButton icon="solar:refresh-linear" label="تحديث" onClick={() => { setLoading(true); void loadRequests().then(setData).catch(cause => setError(String(cause))).finally(() => setLoading(false)); }} /></div>{error && <p role="alert" className="error">{error}</p>}{loading ? <div className="admin-loading">جاري تحميل الطلبات...</div> : filtered.length === 0 ? <div className="admin-empty">لا توجد {heading} مطابقة حاليًا.</div> : <div className="requests-list">{filtered.map(item => { const service = 'service_title' in item; const join = item as JoinRequest; const request = item as ServiceRequest; return <article className="request-card" key={item.id}><div className="request-card-title"><div><strong>{item.name}</strong><span>{service ? request.service_title : join.form_title}</span></div><span className="status-badge">{item.status}</span></div><div className="request-meta"><span>{item.phone}</span><span>{item.email}</span><span>{item.created_at ? new Date(item.created_at).toLocaleDateString('ar-SA') : item.created_at_label || ''}</span></div>{service ? <p className="request-details">{request.details}</p> : <><div className="request-details">{Object.entries(join.fields || {}).map(([key, value]) => <p key={key}><strong>{key}: </strong>{value}</p>)}</div>{join.attachment_path && <button className="admin-link" onClick={async () => { if (!supabase) return; const { data, error } = await supabase.storage.from('join-attachments').createSignedUrl(join.attachment_path!, 60); if (!error && data?.signedUrl) window.open(data.signedUrl, '_blank', 'noopener,noreferrer'); else setError('تعذر فتح المرفق.'); }}>عرض المرفق</button>}</>}<SelectField label="تغيير الحالة" value={item.status} onChange={status => void update(item.id, status)} options={statuses.map(status => [status, status])} />{busy === item.id && <span className="field-hint">جاري الحفظ...</span>}</article>; })}</div>}</>;
}
